/**
 * Created by wangming on 2016/10/28.
 */

/**
 * 已配货表数据
 */
export const haveDistributionListData = [
  {
    CRKSHZT: 0, // 出入库审核状态，虚拟字段，'0' 代表待复核， '1'代表通过
    GUID: 1000001,
    YWXZFL: '业务线ID',
    YWXMC: '脊柱',
    PPID: '品牌ID',
    PPMC: '三友',
    SSLXID: '手术类型ID',
    SSLXMC: '脊椎矫正',
    SSMC: '手术名称',
    SSMBID: '手术模板ID',
    SSMBMC: '雅典娜',
    CJJXSMC: '华仁药业有限公司',
    SHJXSMC: '鼎盛医疗',
    DDZT: 1,
    SHZT: '审核状态',
    WBSHZT: '外部审核状态',
    CJSJ: '2016-10-28',
    XSDB: '销售代表',
    XSDBMC: '张三',
    XSZL: '销售助理',
    XSZLMC: '李四',
    ZXFX: 1,
    YYMC: '浙二医院',
    SHLXR: '张三',
    SHLXRDH: '13588319354',
    SHDZ: '浙江省杭州市上城区武林路131号青春大药房',
    DHRQ: '2016-02-29 10:30',
    DDBZ: '订单备注',
    SSRQ: '手术日期',
    RL: '入路',
    RLMC: '入路名称',
    BW: '部位',
    BWMC: '部位名称',
    YSID: '医生ID',
    YSMC: '医生名称',
    FSYSBH1: '附属医生编号1',
    FSYSMC1: '附属医生名称1',
    FSYSBH2: '附属医生编号2',
    FSYSMC2: '附属医生名称2',
    FSYSBH3: '附属医生编号3',
    FSYSMC3: '附属医生名称3',
    BRXM: '病人姓名',
    BRXB: '病人性别',
    ZYH: '住院号',
    CWH: '床位号',
    DDLX: 1
  },
  {
    CRKSHZT: 0, // 出入库审核状态，虚拟字段，'0' 代表待复核， '1'代表通过
    GUID: 1000002,
    YWXZFL: '业务线ID',
    YWXMC: '脊柱',
    PPID: '品牌ID',
    PPMC: '三友',
    SSLXID: '手术类型ID',
    SSLXMC: '脊椎矫正',
    SSMC: '手术名称',
    SSMBID: '手术模板ID',
    SSMBMC: '雅典娜',
    CJJXSMC: '华仁药业有限公司',
    SHJXSMC: '鼎盛医疗',
    DDZT: 1,
    SHZT: '审核状态',
    WBSHZT: '外部审核状态',
    CJSJ: '2016-10-28',
    XSDB: '销售代表',
    XSDBMC: '张三',
    XSZL: '销售助理',
    XSZLMC: '李四',
    ZXFX: 1,
    YYMC: '浙二医院',
    SHLXR: '张三',
    SHLXRDH: '13588319354',
    SHDZ: '浙江省杭州市上城区武林路131号青春大药房',
    DHRQ: '2016-02-29 10:30',
    DDBZ: '订单备注',
    SSRQ: '手术日期',
    RL: '入路',
    RLMC: '入路名称',
    BW: '部位',
    BWMC: '部位名称',
    YSID: '医生ID',
    YSMC: '医生名称',
    FSYSBH1: '附属医生编号1',
    FSYSMC1: '附属医生名称1',
    FSYSBH2: '附属医生编号2',
    FSYSMC2: '附属医生名称2',
    FSYSBH3: '附属医生编号3',
    FSYSMC3: '附属医生名称3',
    BRXM: '病人姓名',
    BRXB: '病人性别',
    ZYH: '住院号',
    CWH: '床位号',
    DDLX: 1
  },
  {
    CRKSHZT: 1, // 出入库审核状态，虚拟字段，'0' 代表待复核， '1'代表通过
    GUID: 1000003,
    YWXZFL: '业务线ID',
    YWXMC: '脊柱',
    PPID: '品牌ID',
    PPMC: '三友',
    SSLXID: '手术类型ID',
    SSLXMC: '脊椎矫正',
    SSMC: '手术名称',
    SSMBID: '手术模板ID',
    SSMBMC: '雅典娜',
    CJJXSMC: '华仁药业有限公司',
    SHJXSMC: '鼎盛医疗',
    DDZT: 1,
    SHZT: '审核状态',
    WBSHZT: '外部审核状态',
    CJSJ: '2016-10-28',
    XSDB: '销售代表',
    XSDBMC: '张三',
    XSZL: '销售助理',
    XSZLMC: '李四',
    ZXFX: 1,
    YYMC: '浙二医院',
    SHLXR: '张三',
    SHLXRDH: '13588319354',
    SHDZ: '浙江省杭州市上城区武林路131号青春大药房',
    DHRQ: '2016-02-29 10:30',
    DDBZ: '订单备注',
    SSRQ: '手术日期',
    RL: '入路',
    RLMC: '入路名称',
    BW: '部位',
    BWMC: '部位名称',
    YSID: '医生ID',
    YSMC: '医生名称',
    FSYSBH1: '附属医生编号1',
    FSYSMC1: '附属医生名称1',
    FSYSBH2: '附属医生编号2',
    FSYSMC2: '附属医生名称2',
    FSYSBH3: '附属医生编号3',
    FSYSMC3: '附属医生名称3',
    BRXM: '病人姓名',
    BRXB: '病人性别',
    ZYH: '住院号',
    CWH: '床位号',
    DDLX: 1
  }
];

/**
 * 待出库表数据
 */
export const toBeDistributionListData = [
  {
    CKZT: 0, // 出库状态，'0' 代表待出库， '1'代表部分出库
    GUID: 1000001,
    YWXZFL: '业务线ID',
    YWXMC: '脊柱',
    PPID: '品牌ID',
    PPMC: '三友',
    SSLXID: '手术类型ID',
    SSLXMC: '脊椎矫正',
    SSMC: '手术名称',
    SSMBID: '手术模板ID',
    SSMBMC: '雅典娜',
    CJJXSMC: '华仁药业有限公司',
    SHJXSMC: '鼎盛医疗',
    DDZT: 1,
    SHZT: '审核状态',
    WBSHZT: '外部审核状态',
    CJSJ: '2016-10-28',
    XSDB: '销售代表',
    XSDBMC: '张三',
    XSZL: '销售助理',
    XSZLMC: '李四',
    ZXFX: 1,
    YYMC: '浙二医院',
    SHLXR: '张三',
    SHLXRDH: '13588319354',
    SHDZ: '浙江省杭州市上城区武林路131号青春大药房',
    DHRQ: '2016-02-29 10:30',
    DDBZ: '订单备注',
    SSRQ: '手术日期',
    RL: '入路',
    RLMC: '入路名称',
    BW: '部位',
    BWMC: '部位名称',
    YSID: '医生ID',
    YSMC: '医生名称',
    FSYSBH1: '附属医生编号1',
    FSYSMC1: '附属医生名称1',
    FSYSBH2: '附属医生编号2',
    FSYSMC2: '附属医生名称2',
    FSYSBH3: '附属医生编号3',
    FSYSMC3: '附属医生名称3',
    BRXM: '病人姓名',
    BRXB: '病人性别',
    ZYH: '住院号',
    CWH: '床位号',
    DDLX: 1
  },
  {
    CKZT: 0, // 出库状态，'0' 代表待出库， '1'代表部分出库
    GUID: 1000002,
    YWXZFL: '业务线ID',
    YWXMC: '脊柱',
    PPID: '品牌ID',
    PPMC: '三友',
    SSLXID: '手术类型ID',
    SSLXMC: '脊椎矫正',
    SSMC: '手术名称',
    SSMBID: '手术模板ID',
    SSMBMC: '雅典娜',
    CJJXSMC: '华仁药业有限公司',
    SHJXSMC: '鼎盛医疗',
    DDZT: 1,
    SHZT: '审核状态',
    WBSHZT: '外部审核状态',
    CJSJ: '2016-10-28',
    XSDB: '销售代表',
    XSDBMC: '张三',
    XSZL: '销售助理',
    XSZLMC: '李四',
    ZXFX: 1,
    YYMC: '浙二医院',
    SHLXR: '张三',
    SHLXRDH: '13588319354',
    SHDZ: '浙江省杭州市上城区武林路131号青春大药房',
    DHRQ: '2016-02-29 10:30',
    DDBZ: '订单备注',
    SSRQ: '手术日期',
    RL: '入路',
    RLMC: '入路名称',
    BW: '部位',
    BWMC: '部位名称',
    YSID: '医生ID',
    YSMC: '医生名称',
    FSYSBH1: '附属医生编号1',
    FSYSMC1: '附属医生名称1',
    FSYSBH2: '附属医生编号2',
    FSYSMC2: '附属医生名称2',
    FSYSBH3: '附属医生编号3',
    FSYSMC3: '附属医生名称3',
    BRXM: '病人姓名',
    BRXB: '病人性别',
    ZYH: '住院号',
    CWH: '床位号',
    DDLX: 1
  },
  {
    CKZT: 1, // 出库状态，'0' 代表待出库， '1'代表部分出库
    GUID: 1000003,
    YWXZFL: '业务线ID',
    YWXMC: '脊柱',
    PPID: '品牌ID',
    PPMC: '三友',
    SSLXID: '手术类型ID',
    SSLXMC: '脊椎矫正',
    SSMC: '手术名称',
    SSMBID: '手术模板ID',
    SSMBMC: '雅典娜',
    CJJXSMC: '华仁药业有限公司',
    SHJXSMC: '鼎盛医疗',
    DDZT: 1,
    SHZT: '审核状态',
    WBSHZT: '外部审核状态',
    CJSJ: '2016-10-28',
    XSDB: '销售代表',
    XSDBMC: '张三',
    XSZL: '销售助理',
    XSZLMC: '李四',
    ZXFX: 1,
    YYMC: '浙二医院',
    SHLXR: '张三',
    SHLXRDH: '13588319354',
    SHDZ: '浙江省杭州市上城区武林路131号青春大药房',
    DHRQ: '2016-02-29 10:30',
    DDBZ: '订单备注',
    SSRQ: '手术日期',
    RL: '入路',
    RLMC: '入路名称',
    BW: '部位',
    BWMC: '部位名称',
    YSID: '医生ID',
    YSMC: '医生名称',
    FSYSBH1: '附属医生编号1',
    FSYSMC1: '附属医生名称1',
    FSYSBH2: '附属医生编号2',
    FSYSMC2: '附属医生名称2',
    FSYSBH3: '附属医生编号3',
    FSYSMC3: '附属医生名称3',
    BRXM: '病人姓名',
    BRXB: '病人性别',
    ZYH: '住院号',
    CWH: '床位号',
    DDLX: 1
  }
];

export const selectProductionData = [
  {
    CRKID: 10001,
    CKCZR: '张三',
    ZT: 1
  },
  {
    CRKID: 10002,
    CKCZR: '张三',
    ZT: 0
  },
  {
    CRKID: 10003,
    CKCZR: '张三',
    ZT: 1
  },
  {
    CRKID: 10004,
    CKCZR: '张三',
    ZT: 0
  }
];

